apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: alb-ingress
  namespace: bluebird
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: instance
spec:
  rules:
  - host: bluebird.minseok433.shop 
    http:
      paths:
        - path: /back*
          backend:
            serviceName: back
            servicePort: 80
        - path: /*
          backend:
            serviceName: front
            servicePort: 80
  - host: jenkins.minseok433.shop
    http:
      paths:
        - path: /*
          backend:
            serviceName: jenkins-external-svc
            servicePort: 80
