---
apiVersion: v1
kind: Service
metadata:
  name: back
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: back

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-server
  labels:
    app: back                                                                                                                                                          
spec:
  replicas: 1                                                                                                                                                               
  selector:
    matchLabels:                                                                                                                                                            
      app: back                                                                                                                                                           
  template:
    metadata:                                                                                                                                                               
      labels:                                                                                                                                                               
        app: back                                                                                                                                                          
    spec:
      containers:                                                                                                                                                           
      - name: back                                                                                                                                                    
        image: hans9102/backapp:1.0                                                                                                                                         
        ports:                                                                                                                                                              
        - containerPort: 8080                                                                                                                                               
      - name: db                                                                                                                                                          
        image: mongo
