---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
      - name: front
        image: hans9102/frontapp:1.0
        env:
          - name: PROTOCOL
            value: "https"
          - name: REACT_APP_API_SERVER_URL
            value: "$(PROTOCOL)://$(BACK_SERVICE_HOST):$(BACK_SERVICE_PORT)"
        ports:
        - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: front
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: front
---
