apiVersion: v1
kind: ConfigMap
metadata:
    name: web-config
data:
    web.properties: |
        window.API_URL= back
    PORT: "3000"
    URL: mongodb://mongo-0.mongo:27017/mongos?readPreference=secondaryPreferred
    