apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-jenkins
  namespace: jenkins
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: instance
    alb.ingress.kubernetes.io/group.name: "alb-ingress"
spec:
  rules:
  - host: jenkins.minseok433.shop
    http:
      paths:
        - path: /*
          backend:
            serviceName: jenkins
            servicePort: 80
